name: tests-etfdataworker

on:
  pull_request:
    paths:
      - "etf-data-worker/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd etf-data-worker && npm install && npm run test:ci
